Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      MemorySize: 128
      Timeout: 20
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /invoke
            Method: post
